### ISSUE TITLE
Add more professors in AI/ML

### ISSUE THREAD

**Issue by longdct2706** [dynaroars/dynaroars.github.io#1]
Thank you for your list. It is really helpful.
I want to add two more professors in AI/ML that weren't mentioned:

| Name | Univ | Research Areas |
| --------- | ------ | ------------------------|
| [Thien Huu Nguyen](https://ix.cs.uoregon.edu/~thien/) | University of Oregon | Natural Language Processing |
| [Nhat Ho](https://nhatptnk8912.github.io/) | University of Texas at Austin | Stats / ML

**Comment by nguyenthanhvuh** [comment]
thanks, I've added Prof. Thien Huu Nguyen.   

It seems that Prof. Nhat Ho is in the Stats and Data Sciences at UT Austin and is not affiliated to CS to advise CS Ph.D. students. At this moment this list only contains those that can advise CS Ph.D. students.  In the future I plan to create a larger database for all Vietnamese profs in the US.
