### ISSUE TITLE
Request to add Prof. Tam Vu to the list

### ISSUE THREAD

**Issue by lethanh-96** [dynaroars/dynaroars.github.io#11]
Name: Tam Vu
URL: http://mnslab.org/tamvu/
University: Dartmouth College, Earable Neuroscience
Research Area: Earable Computing

**Comment by nguyenthanhvuh** [comment]
thanks,  added in [81fe71b](https://github.com/dynaroars/dynaroars.github.io/wiki/Viet-CS-Profs-US/81fe71bc1f05d2d2ac02e799808c7e8b2bb69009)
